name: Build and deploy Node.js app to Azure Web App - cybertools

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    strategy:
      matrix:
        node-version: [v22.13.1]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: oven-sh/setup-bun@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "bun" # Fixed typo from "ache" to "cache"

      - name: Install dependencies
        run: |
          bun install
          # Install test type definitions to fix compile errors
          bun add -D @types/jest

      - name: Build TypeScript project
        run: |
          # Skip tests during TypeScript compilation
          bun run tsc --skipLibCheck --noEmit false

      - name: Create production build
        run: |
          # Fix the build command to properly compile TypeScript without test files
          bun run tsc --project tsconfig.build.json || bun run tsc --skipLibCheck

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B677371ED1D0420A972785B5DA22C53C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F6DDD1488A524BE0BC46B3BADDD94F28 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3B444BDC7DBF4D6F968D39CFCD2CA6CB }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "cybertools"
          slot-name: "Production"
          package: .
